# .github/release.yml

changelog:
  exclude:
    labels:
      - abaikan-rilis
      - dokumentasi
    authors:
      - octocat
  categories:
    - title: 🚀 Peningkatan
      labels:
        - peningkatan
    - title: 🛠️ Perbaikan
      labels:
        - perbaikan
        - bug
    - title: ➡️ Lain-lain
      labels:
        - "*"
