blank_issues_enabled: false
contact_links:
  - name: Kirim Pertanyaan
    url: https://github.com/ataslangit/sistem-informasi-desa/discussions/new
    about: Ajukan pertanyaan terkait SID

  - name: Kolom Tanya-Jawab
    url: https://github.com/ataslangit/sistem-informasi-desa/discussions
    about: Tanya-Jawab seputar SID

  - name: Panduan SID
    url: https://ataslangit.github.io/
    about: Panduan Sistem Informasi Desa
