blank_issues_enabled: false
contact_links:
  - name: Diskusi terkait SID
    url: https://github.com/ataslangit/sistem-informasi-desa/discussions
    about: Silakan ajukan pertanyaan dan jawab jika berkenan
  - name: Panduan SID
    url: https://ataslangit.github.io/sistem-informasi-desa/
    about: Panduan terkait SID
