<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Artikel extends Seeder
{
    public function run()
    {
        $builder = $this->db->table('artikel');

        $builder->insertBatch([
            [
                'id'           => 1,
                'gambar'       => '1485865098',
                'isi'          => '<div class="teks" style="text-align: justify;"><div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:18:18',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Profil Desa',
                'headline'     => 0,
                'gambar1'      => '1485865098',
                'gambar2'      => '1485865098',
                'gambar3'      => '1485865098',
                'dokumen'      => '',
                'link_dokumen' => 'Profil Desa',
            ],
            [
                'id'           => 2,
                'gambar'       => '1485865119',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:18:39',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Sejarah Desa',
                'headline'     => 0,
                'gambar1'      => '1485865119',
                'gambar2'      => '1485865119',
                'gambar3'      => '1485865119',
                'dokumen'      => '',
                'link_dokumen' => 'Sejarah Desa',
            ],
            [
                'id'           => 3,
                'gambar'       => '1485865147',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:19:07',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Kondisi Umum Desa',
                'headline'     => 0,
                'gambar1'      => '1485865147',
                'gambar2'      => '1485865147',
                'gambar3'      => '1485865147',
                'dokumen'      => '',
                'link_dokumen' => 'Kondisi Umum Desa',
            ],
            [
                'id'           => 4,
                'gambar'       => '1485865186',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:19:46',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Masalah & Isu Strategis Desa',
                'headline'     => 0,
                'gambar1'      => '1485865186',
                'gambar2'      => '1485865186',
                'gambar3'      => '1485865186',
                'dokumen'      => '',
                'link_dokumen' => 'Masalah & Isu Strategis Desa',
            ],
            [
                'id'           => 5,
                'gambar'       => '1485865223',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:20:23',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Kebijakan Pembangunan Desa',
                'headline'     => 0,
                'gambar1'      => '1485865223',
                'gambar2'      => '1485865223',
                'gambar3'      => '1485865223',
                'dokumen'      => '',
                'link_dokumen' => 'Kebijakan Pembangunan Desa',
            ],
            [
                'id'           => 6,
                'gambar'       => '1485865252',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:20:52',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Kebijakan Keuangan Desa',
                'headline'     => 0,
                'gambar1'      => '1485865252',
                'gambar2'      => '1485865252',
                'gambar3'      => '1485865252',
                'dokumen'      => '',
                'link_dokumen' => 'Kebijakan Keuangan Desa',
            ],
            [
                'id'           => 7,
                'gambar'       => '1485865283',
                'isi'          => '<div class="teks" style="text-align: justify;"><div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:21:23',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Pemerintahan Desa',
                'headline'     => 0,
                'gambar1'      => '1485865283',
                'gambar2'      => '1485865283',
                'gambar3'      => '1485865283',
                'dokumen'      => '',
                'link_dokumen' => 'Pemerintahan Desa',
            ],
            [
                'id'           => 8,
                'gambar'       => '14864630082017 02 - Contoh Foto SID 3.10 d.jpg',
                'isi'          => '<p>Profil Kepala Desa Bumi Pertiwi</p><div class="teks" style="text-align: justify;"><div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:21:51',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Kepala Desa',
                'headline'     => 0,
                'gambar1'      => '1485865311',
                'gambar2'      => '1485865311',
                'gambar3'      => '1485865311',
                'dokumen'      => '',
                'link_dokumen' => 'Kepala Desa',
            ],
            [
                'id'           => 9,
                'gambar'       => '1485865337',
                'isi'          => '<p>Sekretaris Desa:</p><p>Kaur/Kabag Keuangan:</p><p>Staf Kaur/Kabag Keuangan:</p><p>Kaur/Kabag Pemerintahan:</p><p>Staf Kaur/Kabag Pemerintahan:</p><p>Kaur/Kabag Kesejahteraan Rakyat:</p><p>Staf Kaur/Kabag Kesejahteraan Rakyat:</p><p>Kaur/Kabag Ekonomi dan Pembangunan:</p><p>Staf Kaur/Kaba Ekonomi dan Pembangunan</p><p>Kepala Dusun A:</p><p>Kepala Dusun B:</p><p>Kepala Dusun C:</p><p>Kepala Dusun D:</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:22:17',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Perangkat Desa',
                'headline'     => 0,
                'gambar1'      => '1485865337',
                'gambar2'      => '1485865337',
                'gambar3'      => '1485865337',
                'dokumen'      => '',
                'link_dokumen' => 'Perangkat Desa',
            ],
            [
                'id'           => 10,
                'gambar'       => '1485865366',
                'isi'          => '<p>Ketua:</p><p>Wakil Ketua:</p><p>Anggota:</p><p>1.</p><p>2.</p><p>3.</p><p>4.</p><p>5.</p><p>&nbsp;</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:22:46',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Badan Permusyawaratan Desa',
                'headline'     => 0,
                'gambar1'      => '1485865366',
                'gambar2'      => '1485865366',
                'gambar3'      => '1485865366',
                'dokumen'      => '',
                'link_dokumen' => 'Badan Permusyawaratan Desa',
            ],
            [
                'id'           => 11,
                'gambar'       => '1485865388',
                'isi'          => '<p>Lembaga Masyarakat Desa</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:23:08',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Lembaga Masyarakat Desa',
                'headline'     => 0,
                'gambar1'      => '1485865388',
                'gambar2'      => '1485865388',
                'gambar3'      => '1485865388',
                'dokumen'      => '',
                'link_dokumen' => 'Lembaga Masyarakat Desa',
            ],
            [
                'id'           => 12,
                'gambar'       => '1485865408',
                'isi'          => '<div class="teks" style="text-align: justify;"><div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:23:28',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'LPMD',
                'headline'     => 0,
                'gambar1'      => '1485865408',
                'gambar2'      => '1485865408',
                'gambar3'      => '1485865408',
                'dokumen'      => '',
                'link_dokumen' => 'LPMD',
            ],
            [
                'id'           => 13,
                'gambar'       => '1485865431',
                'isi'          => '<div class="teks" style="text-align: justify;"><div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:23:51',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Lembaga Adat',
                'headline'     => 0,
                'gambar1'      => '1485865431',
                'gambar2'      => '1485865431',
                'gambar3'      => '1485865431',
                'dokumen'      => '',
                'link_dokumen' => 'Lembaga Adat',
            ],
            [
                'id'           => 14,
                'gambar'       => '1485865456',
                'isi'          => '<p>Tim Penggerak PKK</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:24:16',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'TP PKK',
                'headline'     => 0,
                'gambar1'      => '1485865456',
                'gambar2'      => '1485865456',
                'gambar3'      => '1485865456',
                'dokumen'      => '',
                'link_dokumen' => 'TP PKK',
            ],
            [
                'id'           => 15,
                'gambar'       => '1485865479',
                'isi'          => '<div class="teks" style="text-align: justify;"><div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:24:39',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'BUMDes',
                'headline'     => 0,
                'gambar1'      => '1485865479',
                'gambar2'      => '1485865479',
                'gambar3'      => '1485865479',
                'dokumen'      => '',
                'link_dokumen' => 'BUMDes',
            ],
            [
                'id'           => 16,
                'gambar'       => '1485865503',
                'isi'          => '<p>Ketua:</p><p>Wakil Ketua:</p><p>Sekretaris:</p><p>Bendahara:</p><p>Anggota:</p><p>&nbsp;</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:25:03',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Karang Taruna',
                'headline'     => 0,
                'gambar1'      => '1485865503',
                'gambar2'      => '1485865503',
                'gambar3'      => '1485865503',
                'dokumen'      => '',
                'link_dokumen' => 'Karang Taruna',
            ],
            [
                'id'           => 17,
                'gambar'       => '1485865535',
                'isi'          => '<p>Dusun A:</p><p>Ketua RW 01:</p><p>Sekretaris RW 01:</p><p>Bendahara RW 01:</p><p>Ketua RT 01</p><p>Ketua RT 02</p><p>Ketua RT 03</p><p>&nbsp;</p><p>Ketua RW 02:</p><p>Sekretaris RW 02:</p><p>Bendahara RW 02:</p><p>Ketua RT 04</p><p>Ketua RT 05</p><p>Ketua RT 06</p><p>&nbsp;</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:25:35',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'RT/RW',
                'headline'     => 0,
                'gambar1'      => '1485865535',
                'gambar2'      => '1485865535',
                'gambar3'      => '1485865535',
                'dokumen'      => '',
                'link_dokumen' => 'RT/RW',
            ],
            [
                'id'           => 18,
                'gambar'       => '1485865556',
                'isi'          => '<p>Ketua:</p><p>Anggota:</p><p>1.</p><p>2.</p><p>3.</p><p>4.</p><p>5.</p><p>&nbsp;</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:25:56',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Linmas',
                'headline'     => 0,
                'gambar1'      => '1485865556',
                'gambar2'      => '1485865556',
                'gambar3'      => '1485865556',
                'dokumen'      => '',
                'link_dokumen' => 'Linmas',
            ],
            [
                'id'           => 19,
                'gambar'       => '1485865581',
                'isi'          => '<div class="teks" style="text-align: justify;"><div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:26:21',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Lembaga Masyarakat Lainnya',
                'headline'     => 0,
                'gambar1'      => '1485865581',
                'gambar2'      => '1485865581',
                'gambar3'      => '1485865581',
                'dokumen'      => '',
                'link_dokumen' => 'Lembaga Masyarakat Lainnya',
            ],
            [
                'id'           => 20,
                'gambar'       => '1485865605',
                'isi'          => '<div class="teks" style="text-align: justify;"><p style="text-align: justify;">Halaman ini berisi tautan menuju informasi mengenai Basis Data Desa. Ada dua jenis data yang dikelola dalam sistem ini, yakni basis data kependudukan dan basis data sumber daya desa. Sila klik pada tautan berikut untuk mendapatkan tampilan data statistik per kategori.</p><ol><li style="text-align: justify;"><class="statistik/wilayah">Data Wilayah Administratif </li><li style="text-align: justify;"><class="statistik/pendidikan-dalam-kk">Data Pendidikan dalam Kartu Keluarga </li><li style="text-align: justify;"><class="statistik/pendidikan-ditempuh">Data Pendidikan sedang Ditempuh </li><li style="text-align: justify;"><class="statistik/pekerjaan">Data Pekerjaan </li><li style="text-align: justify;"><class="statistik/agama">Data Agama &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;</li><li style="text-align: justify;"><class="statistik/jenis-kelamin">Data Jenis Kelamin</li><li style="text-align: justify;"><class="statistik/golongan-darah">Data Golongan Darah</li><li style="text-align: justify;"><class="statistik/kelompok-umur">Data Kelompok Umur </li><li style="text-align: justify;"><class="statistik/warga-negara">Data Warga Negara </li><li style="text-align: justify;"><class="statistik/status-perkawinan">Data Status Perkawinan </li><li style="text-align: justify;"><class="data_analisis">Data Analisis Sumber Daya</li></ol><p style="text-align: justify;">&nbsp;</p><p style="text-align: justify;">Data yang tampil adalah statistik yang didapatkan dari proses olah data yang dilakukan oleh pemerintah desa secara rutin/harian atau berkala/per periode, baik secara <em>offline</em> maupun <em>online</em>. Sila hubungi kontak pemerintah desa jika perlu akses untuk mendapatkan data dan informasi desa yang lebih lengkap dan termutakhir.</p><p style="text-align: justify;">&nbsp;</p><p style="text-align: justify;">&nbsp;</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:26:45',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Data Desa',
                'headline'     => 0,
                'gambar1'      => '1485865605',
                'gambar2'      => '1485865605',
                'gambar3'      => '1485865605',
                'dokumen'      => '',
                'link_dokumen' => 'Data Desa',
            ],
            [
                'id'           => 21,
                'gambar'       => '1485865659',
                'isi'          => '<p>Anda dapat menghubungi kami di:</p><p>Alamat: ......</p><p>Telepon/HP: .....</p><p>e-mail: ....</p><p>&nbsp;</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:27:39',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Kontak Desa',
                'headline'     => 0,
                'gambar1'      => '1485865659',
                'gambar2'      => '1485865659',
                'gambar3'      => '1485865659',
                'dokumen'      => '',
                'link_dokumen' => 'Kontak Desa',
            ],
            [
                'id'           => 22,
                'gambar'       => '1485866915',
                'isi'          => '<p>VISI:</p><div class="teks" style="text-align: justify;"><div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p><p>&nbsp;</p><p>MISI:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-01-31 12:48:35',
                'id_kategori'  => 999,
                'id_user'      => 61,
                'judul'        => 'Visi dan Misi',
                'headline'     => 0,
                'gambar1'      => '1485866915',
                'gambar2'      => '1485866915',
                'gambar3'      => '1485866915',
                'dokumen'      => '',
                'link_dokumen' => 'Visi dan Misi',
            ],
            [
                'id'           => 23,
                'gambar'       => '14859353562017 02 - Contoh Foto SID 3.10.jpg',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>&nbsp;</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 07:49:16',
                'id_kategori'  => 6,
                'id_user'      => 61,
                'judul'        => 'Dokumen RPJM Desa Bumi Pertiwi 2017-2022',
                'headline'     => 0,
                'gambar1'      => '1485935356',
                'gambar2'      => '1485935356',
                'gambar3'      => '1485935356',
                'dokumen'      => '2017 02 - Contoh Lampiran SID 3.10.pdf',
                'link_dokumen' => 'Dokumen RPJM Desa Bumi Pertiwi 2017-2022',
            ],
            [
                'id'           => 24,
                'gambar'       => '14859357502017 02 - Contoh Foto SID 3.10.jpg',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>&nbsp;</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 07:55:50',
                'id_kategori'  => 8,
                'id_user'      => 61,
                'judul'        => 'LPJ Kepala Desa Bumi Pertiwi 2010-2016',
                'headline'     => 0,
                'gambar1'      => '1485935750',
                'gambar2'      => '1485935750',
                'gambar3'      => '1485935750',
                'dokumen'      => '2017 02 - Contoh Lampiran SID 3.10.pdf',
                'link_dokumen' => 'LPJ Kepala Desa Bumi Pertiwi 2010-2016',
            ],
            [
                'id'           => 25,
                'gambar'       => '14859362362017 02 - Contoh Foto SID 3.10 c.jpg',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>&nbsp;</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:03:57',
                'id_kategori'  => 5,
                'id_user'      => 61,
                'judul'        => 'Perdes No 15/2016 tentang Pengelolaan Pasar Desa',
                'headline'     => 0,
                'gambar1'      => '1485936236',
                'gambar2'      => '1485936236',
                'gambar3'      => '1485936236',
                'dokumen'      => '2017 02 - Contoh Lampiran SID 3.10.pdf',
                'link_dokumen' => 'Perdes No 15/2016 tentang Pengelolaan Pasar Desa',
            ],
            [
                'id'           => 26,
                'gambar'       => '14859369972017 02 - Contoh Foto SID 3.10 d.jpg',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:16:37',
                'id_kategori'  => 19,
                'id_user'      => 61,
                'judul'        => 'Objek Wisata Air Terjun Bumi Pertiwi',
                'headline'     => 0,
                'gambar1'      => '1485936997',
                'gambar2'      => '1485936997',
                'gambar3'      => '1485936997',
                'dokumen'      => '',
                'link_dokumen' => 'Objek Wisata Air Terjun Bumi Pertiwi',
            ],
            [
                'id'           => 27,
                'gambar'       => '14859370772017 02 - Contoh Foto SID 3.10 b.jpg',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:17:57',
                'id_kategori'  => 19,
                'id_user'      => 61,
                'judul'        => 'Kerajinan Pahat Batu Dusun Sabak Mendunia',
                'headline'     => 0,
                'gambar1'      => '1485937077',
                'gambar2'      => '1485937077',
                'gambar3'      => '1485937077',
                'dokumen'      => '',
                'link_dokumen' => 'Kerajinan Pahat Batu Dusun Sabak Mendunia',
            ],
            [
                'id'           => 28,
                'gambar'       => '14859371542017 02 - Contoh Foto SID 3.10.jpg',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:19:14',
                'id_kategori'  => 1,
                'id_user'      => 61,
                'judul'        => 'Pilkades Bumi Pertiwi Diikuti 7 Calon',
                'headline'     => 0,
                'gambar1'      => '1485937154',
                'gambar2'      => '1485937154',
                'gambar3'      => '1485937154',
                'dokumen'      => '',
                'link_dokumen' => 'Pilkades Bumi Pertiwi Diikuti 7 Calon',
            ],
            [
                'id'           => 29,
                'gambar'       => '14859372842017 02 - Contoh Foto SID 3.10 c.jpg',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:21:24',
                'id_kategori'  => 1,
                'id_user'      => 61,
                'judul'        => 'Kades Canangkan Program Kesehatan Rumah Tangga',
                'headline'     => 0,
                'gambar1'      => '1485937284',
                'gambar2'      => '1485937284',
                'gambar3'      => '1485937284',
                'dokumen'      => '',
                'link_dokumen' => 'Kades Canangkan Program Kesehatan Rumah Tangga',
            ],
            [
                'id'           => 30,
                'gambar'       => '1485937344',
                'isi'          => '<ol><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</li><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</li></ol>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:22:24',
                'id_kategori'  => 1000,
                'id_user'      => 61,
                'judul'        => 'Agenda Desa per Januari 2017',
                'headline'     => 0,
                'gambar1'      => '1485937344',
                'gambar2'      => '1485937344',
                'gambar3'      => '1485937344',
                'dokumen'      => '',
                'link_dokumen' => 'Agenda Desa per Januari 2017',
            ],
            [
                'id'           => 31,
                'gambar'       => '1485937404',
                'isi'          => '<ol><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</li><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</li></ol>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:23:24',
                'id_kategori'  => 4,
                'id_user'      => 61,
                'judul'        => 'Agenda Kegiatan Desa Bumi Pertiwi per Januari 2017',
                'headline'     => 0,
                'gambar1'      => '1485937404',
                'gambar2'      => '1485937404',
                'gambar3'      => '1485937404',
                'dokumen'      => '',
                'link_dokumen' => 'Agenda Kegiatan Desa Bumi Pertiwi per Januari 2017',
            ],
            [
                'id'           => 32,
                'gambar'       => '14859374622017 02 - Contoh Foto SID 3.10 b.jpg',
                'isi'          => '<ol><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</li><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</li></ol>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:24:23',
                'id_kategori'  => 4,
                'id_user'      => 61,
                'judul'        => 'Agenda Kegiatan Desa Bumi Pertiwi per Februari 2017',
                'headline'     => 0,
                'gambar1'      => '1485937462',
                'gambar2'      => '1485937462',
                'gambar3'      => '1485937462',
                'dokumen'      => '',
                'link_dokumen' => 'Agenda Kegiatan Desa Bumi Pertiwi per Februari 2017',
            ],
            [
                'id'           => 33,
                'gambar'       => '1485937843',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:30:43',
                'id_kategori'  => 18,
                'id_user'      => 61,
                'judul'        => 'Panduan Pelayanan Satu Pintu Desa Bumi Pertiwi',
                'headline'     => 0,
                'gambar1'      => '1485937843',
                'gambar2'      => '1485937843',
                'gambar3'      => '1485937843',
                'dokumen'      => '2017 02 - Contoh Lampiran SID 3.10.pdf',
                'link_dokumen' => 'Panduan Pelayanan Satu Pintu Desa Bumi Pertiwi',
            ],
            [
                'id'           => 34,
                'gambar'       => '14859379462017 02 - Contoh Foto SID 3.10.jpg',
                'isi'          => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-01 08:32:26',
                'id_kategori'  => 1,
                'id_user'      => 61,
                'judul'        => 'Presiden RI Kunjungi Desa Bumi Pertiwi',
                'headline'     => 1,
                'gambar1'      => '1485937946',
                'gambar2'      => '1485937946',
                'gambar3'      => '1485937946',
                'dokumen'      => '',
                'link_dokumen' => 'Presiden RI Kunjungi Desa Bumi Pertiwi',
            ],
            [
                'id'           => 35,
                'gambar'       => '1486320009',
                'isi'          => '<p>Selamat datang di website Desa Bumi Pertiwi.</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-05 18:40:09',
                'id_kategori'  => 17,
                'id_user'      => 61,
                'judul'        => 'Selamat Datang',
                'headline'     => 0,
                'gambar1'      => '1486320009',
                'gambar2'      => '1486320009',
                'gambar3'      => '1486320009',
                'dokumen'      => '',
                'link_dokumen' => 'Selamat Datang',
            ],
            [
                'id'           => 36,
                'gambar'       => '1486320072',
                'isi'          => '<p>Kantor Desa Bumi Pertiwi membuka pelayanan publik pada hari Senin - Sabtu pukul 08.00 - 15.00.</p>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-05 18:41:12',
                'id_kategori'  => 17,
                'id_user'      => 61,
                'judul'        => 'Jam Kerja Kantor Desa',
                'headline'     => 0,
                'gambar1'      => '1486320072',
                'gambar2'      => '1486320072',
                'gambar3'      => '1486320072',
                'dokumen'      => '',
                'link_dokumen' => 'Jam Kerja Kantor Desa',
            ],
            [
                'id'           => 37,
                'gambar'       => '1486462195',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-07 10:09:55',
                'id_kategori'  => 5,
                'id_user'      => 61,
                'judul'        => 'SK Operator SID',
                'headline'     => 0,
                'gambar1'      => '1486462195',
                'gambar2'      => '1486462195',
                'gambar3'      => '1486462195',
                'dokumen'      => '2017 02 - Contoh Lampiran SID 3.10.pdf',
                'link_dokumen' => 'SK Operator SID',
            ],
            [
                'id'           => 38,
                'gambar'       => '14864640472017 02 - Contoh Foto SID 3.10 d.jpg',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-07 10:40:47',
                'id_kategori'  => 1,
                'id_user'      => 61,
                'judul'        => 'Pelatihan Jurnalistik untuk Pegiat Karang Taruna',
                'headline'     => 0,
                'gambar1'      => '1486464047',
                'gambar2'      => '1486464047',
                'gambar3'      => '1486464047',
                'dokumen'      => '',
                'link_dokumen' => 'Pelatihan Jurnalistik untuk Pegiat Karang Taruna',
            ],
            [
                'id'           => 39,
                'gambar'       => '1486464155',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-07 10:42:35',
                'id_kategori'  => 1,
                'id_user'      => 61,
                'judul'        => 'Gotong Royong Pemugaran Masjid Desa ',
                'headline'     => 0,
                'gambar1'      => '1486464155',
                'gambar2'      => '1486464155',
                'gambar3'      => '1486464155',
                'dokumen'      => '',
                'link_dokumen' => 'Gotong Royong Pemugaran Masjid Desa ',
            ],
            [
                'id'           => 40,
                'gambar'       => '14864642872017 02 - Contoh Foto SID 3.10 c.jpg',
                'isi'          => '<div class="teks" style="text-align: justify;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris est laborum.</p></div>',
                'enabled'      => 1,
                'tgl_upload'   => '2017-02-07 10:44:10',
                'id_kategori'  => 1,
                'id_user'      => 61,
                'judul'        => 'PKK Desa Bumi Pertiwi Raih Juara 1 Tingkat Kabupaten',
                'headline'     => 0,
                'gambar1'      => '1486464250',
                'gambar2'      => '1486464250',
                'gambar3'      => '1486464250',
                'dokumen'      => '2017 02 - Contoh Foto SID 3.10 c.jpg',
                'link_dokumen' => 'PKK Desa Bumi Pertiwi Raih Juara 1 Tingkat Kabupaten',
            ],
        ]);
    }
}
