<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TwebSuratFormat extends Seeder
{
    public function run()
    {
        $builder = $this->db->table('tweb_surat_format');

        $builder->insertBatch([
            [
                'id'         => 1,
                'nama'       => 'Keterangan',
                'url_surat'  => 'surat_ket_pengantar',
                'kode_surat' => 'F1',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 2,
                'nama'       => 'Keterangan Penduduk',
                'url_surat'  => 'surat_ket_penduduk',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 3,
                'nama'       => 'Biodata Penduduk',
                'url_surat'  => 'surat_bio_penduduk',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 4,
                'nama'       => 'Keterangan Pindah Penduduk',
                'url_surat'  => 'surat_ket_pindah_penduduk',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 5,
                'nama'       => 'Keterangan Jual Beli',
                'url_surat'  => 'surat_ket_jual_beli',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 6,
                'nama'       => 'Pengantar Pindah Antar Kabupaten/ Provinsi',
                'url_surat'  => 'surat_pindah_antar_kab_prov',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 7,
                'nama'       => 'Pengantar SKCK',
                'url_surat'  => 'surat_ket_catatan_kriminal',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 8,
                'nama'       => 'Keterangan KTP dalam Proses',
                'url_surat'  => 'surat_ket_ktp_dlm_proses',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 9,
                'nama'       => 'Keterangan Beda Nama',
                'url_surat'  => 'surat_ket_beda_nama',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 10,
                'nama'       => 'Keterangan Bepergian / Jalan',
                'url_surat'  => 'surat_jalan',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 11,
                'nama'       => 'Keterangan Kurang Mampu',
                'url_surat'  => 'surat_ket_kurang_mampu',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 12,
                'nama'       => 'Pengantar Izin Keramaian',
                'url_surat'  => 'surat_izin_keramaian',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 13,
                'nama'       => 'Pengantar Laporan Kehilangan',
                'url_surat'  => 'surat_lap_kehilangan',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 14,
                'nama'       => 'Keterangan Usaha',
                'url_surat'  => 'surat_ket_usaha',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 16,
                'nama'       => 'Keterangan Domisili Usaha',
                'url_surat'  => 'surat_ket_domisili_usaha',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 17,
                'nama'       => 'Keterangan Kelahiran',
                'url_surat'  => 'surat_ket_kelahiran',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 18,
                'nama'       => 'Keterangan Kehilangan',
                'url_surat'  => 'surat_ket_kehilangan',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 19,
                'nama'       => 'Permohonan Akta Lahir',
                'url_surat'  => 'surat_permohonan_akta',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 20,
                'nama'       => 'Pernyataan Akta Lahir',
                'url_surat'  => 'surat_pernyataan_akta',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 21,
                'nama'       => 'Permohonan Duplikat Kelahiran',
                'url_surat'  => 'surat_permohonan_duplikat_kelahiran',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 22,
                'nama'       => 'Keterangan Kematian',
                'url_surat'  => 'surat_ket_kematian',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 23,
                'nama'       => 'Keterangan Lahir Mati',
                'url_surat'  => 'surat_ket_lahir_mati',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 24,
                'nama'       => 'Keterangan Untuk Nikah (N-1)',
                'url_surat'  => 'surat_ket_nikah',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 25,
                'nama'       => 'Keterangan Asal Usul (N-2)',
                'url_surat'  => 'surat_ket_asalusul',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 26,
                'nama'       => 'Persetujuan Mempelai (N-3)',
                'url_surat'  => 'surat_persetujuan_mempelai',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 27,
                'nama'       => 'Keterangan Tentang Orang Tua (N-4)',
                'url_surat'  => 'surat_ket_orangtua',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 28,
                'nama'       => 'Izin Orang Tua(N-5)',
                'url_surat'  => 'surat_izin_orangtua',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 29,
                'nama'       => 'Keterangan Kematian Suami/Istri(N-6)',
                'url_surat'  => 'surat_ket_kematian_suami_istri',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
            [
                'id'         => 30,
                'nama'       => 'Pemberitahuan Kehendak Nikah (N-7)',
                'url_surat'  => 'surat_kehendak_nikah',
                'kode_surat' => 'FS-00X/DES',
                'kunci'      => 0,
                'favorit'    => 0,
            ],
        ]);
    }
}
