<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TwebPendudukPekerjaan extends Seeder
{
    public function run()
    {
        $builder = $this->db->table('tweb_penduduk_pekerjaan');

        $builder->insertBatch([
            ['id' => 1, 'nama' => 'BELUM/ TIDAK BEKERJA'],
            ['id' => 2, 'nama' => 'MENGURUS RUMAH TANGGA'],
            ['id' => 3, 'nama' => 'PELAJAR/ MAHASISWA'],
            ['id' => 4, 'nama' => 'PENSIUNAN'],
            ['id' => 5, 'nama' => 'PEGAWAI NEGERI SIPIL (PNS)'],
            ['id' => 6, 'nama' => 'TENTARA NASIONAL INDONESIA (TNI)'],
            ['id' => 7, 'nama' => 'KEPOLISIAN RI (POLRI)'],
            ['id' => 8, 'nama' => 'PERDAGANGAN'],
            ['id' => 9, 'nama' => 'PETANI/ PERKEBUNAN'],
            ['id' => 10, 'nama' => 'PETERNAK'],
            ['id' => 11, 'nama' => 'NELAYAN/ PERIKANAN'],
            ['id' => 12, 'nama' => 'INDUSTRI'],
            ['id' => 13, 'nama' => 'KONSTRUKSI'],
            ['id' => 14, 'nama' => 'TRANSPORTASI'],
            ['id' => 15, 'nama' => 'KARYAWAN SWASTA'],
            ['id' => 16, 'nama' => 'KARYAWAN BUMN'],
            ['id' => 17, 'nama' => 'KARYAWAN BUMD'],
            ['id' => 18, 'nama' => 'KARYAWAN HONORER'],
            ['id' => 19, 'nama' => 'BURUH HARIAN LEPAS'],
            ['id' => 20, 'nama' => 'BURUH TANI/ PERKEBUNAN'],
            ['id' => 21, 'nama' => 'BURUH NELAYAN/ PERIKANAN'],
            ['id' => 22, 'nama' => 'BURUH PETERNAKAN'],
            ['id' => 23, 'nama' => 'PEMBANTU RUMAH TANGGA'],
            ['id' => 24, 'nama' => 'TUKANG CUKUR'],
            ['id' => 25, 'nama' => 'TUKANG LISTRIK'],
            ['id' => 26, 'nama' => 'TUKANG BATU'],
            ['id' => 27, 'nama' => 'TUKANG KAYU'],
            ['id' => 28, 'nama' => 'TUKANG SOL SEPATU'],
            ['id' => 29, 'nama' => 'TUKANG LAS/ PANDAI BESI'],
            ['id' => 30, 'nama' => 'TUKANG JAHIT'],
            ['id' => 31, 'nama' => 'TUKANG GIGI'],
            ['id' => 32, 'nama' => 'PENATA RIAS'],
            ['id' => 33, 'nama' => 'PENATA BUSANA'],
            ['id' => 34, 'nama' => 'PENATA RAMBUT'],
            ['id' => 35, 'nama' => 'MEKANIK'],
            ['id' => 36, 'nama' => 'SENIMAN'],
            ['id' => 37, 'nama' => 'TABIB'],
            ['id' => 38, 'nama' => 'PARAJI'],
            ['id' => 39, 'nama' => 'PERANCANG BUSANA'],
            ['id' => 40, 'nama' => 'PENTERJEMAH'],
            ['id' => 41, 'nama' => 'IMAM MASJID'],
            ['id' => 42, 'nama' => 'PENDETA'],
            ['id' => 43, 'nama' => 'PASTOR'],
            ['id' => 44, 'nama' => 'WARTAWAN'],
            ['id' => 45, 'nama' => 'USTADZ/ MUBALIGH'],
            ['id' => 46, 'nama' => 'JURU MASAK'],
            ['id' => 47, 'nama' => 'PROMOTOR ACARA'],
            ['id' => 48, 'nama' => 'ANGGOTA DPR-RI'],
            ['id' => 49, 'nama' => 'ANGGOTA DPD'],
            ['id' => 50, 'nama' => 'ANGGOTA BPK'],
            ['id' => 51, 'nama' => 'PRESIDEN'],
            ['id' => 52, 'nama' => 'WAKIL PRESIDEN'],
            ['id' => 53, 'nama' => 'ANGGOTA MAHKAMAH KONSTITUSI'],
            ['id' => 54, 'nama' => 'ANGGOTA KABINET KEMENTERIAN'],
            ['id' => 55, 'nama' => 'DUTA BESAR'],
            ['id' => 56, 'nama' => 'GUBERNUR'],
            ['id' => 57, 'nama' => 'WAKIL GUBERNUR'],
            ['id' => 58, 'nama' => 'BUPATI'],
            ['id' => 59, 'nama' => 'WAKIL BUPATI'],
            ['id' => 60, 'nama' => 'WALIKOTA'],
            ['id' => 61, 'nama' => 'WAKIL WALIKOTA'],
            ['id' => 62, 'nama' => 'ANGGOTA DPRD PROVINSI'],
            ['id' => 63, 'nama' => 'ANGGOTA DPRD KABUPATEN/ KOTA'],
            ['id' => 64, 'nama' => 'DOSEN'],
            ['id' => 65, 'nama' => 'GURU'],
            ['id' => 66, 'nama' => 'PILOT'],
            ['id' => 67, 'nama' => 'PENGACARA'],
            ['id' => 68, 'nama' => 'NOTARIS'],
            ['id' => 69, 'nama' => 'ARSITEK'],
            ['id' => 70, 'nama' => 'AKUNTAN'],
            ['id' => 71, 'nama' => 'KONSULTAN'],
            ['id' => 72, 'nama' => 'DOKTER'],
            ['id' => 73, 'nama' => 'BIDAN'],
            ['id' => 74, 'nama' => 'PERAWAT'],
            ['id' => 75, 'nama' => 'APOTEKER'],
            ['id' => 76, 'nama' => 'PSIKIATER/ PSIKOLOG'],
            ['id' => 77, 'nama' => 'PENYIAR TELEVISI'],
            ['id' => 78, 'nama' => 'PENYIAR RADIO'],
            ['id' => 79, 'nama' => 'PELAUT'],
            ['id' => 80, 'nama' => 'PENELITI'],
            ['id' => 81, 'nama' => 'SOPIR'],
            ['id' => 82, 'nama' => 'PIALANG'],
            ['id' => 83, 'nama' => 'PARANORMAL'],
            ['id' => 84, 'nama' => 'PEDAGANG'],
            ['id' => 85, 'nama' => 'PERANGKAT DESA'],
            ['id' => 86, 'nama' => 'KEPALA DESA'],
            ['id' => 87, 'nama' => 'BIARAWATI'],
            ['id' => 88, 'nama' => 'WIRASWASTA'],
            ['id' => 89, 'nama' => 'LAINNYA'],
        ]);
    }
}
