name: ASSETS

on:
  pull_request:
    branches:
      - "dev"
    paths:
      - ".github/workflows/assets.yml"
      - "resources/**"
      - "package.json"
      - "package-lock.json"

jobs:
  build:
    name: Generator
    if: github.repository == 'ataslangit/sistem-informasi-desa'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependency
        run: npm ci
      - name: Generate
        run: npm run build
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Assets auto generate"
