name: Squash, Merge & Lock

on: issue_comment

jobs:
  squash_merge:
    if: ${{ github.event.issue.pull_request && github.event.comment.user.id == 2387514}}
    runs-on: ubuntu-latest
    outputs:
      merged: ${{ steps.squashmerge.outputs.mergeResult == 'merged' }}
    steps:
      - name: Squash & Merge
        id: squashmerge
        if: startsWith(github.event.comment.body, '/merge')
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "(#${{ github.event.issue.number }})  ${{ github.event.issue.title }}"
          MERGE_REMOVE_LABELS: "automerge"
      
  lock_PR:
    needs: squash_merge
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.squash_merge.outputs.merged }}
        name: lock PR
        uses: sudo-bot/action-pull-request-lock@v1.1.0
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            number: ${{ github.event.issue.number }}
  
