name: Squash, Merge & Lock

on: issue_comment

jobs:
  squash_merge:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      merged: ${{ steps.squashmerge.outputs.mergeResult }}
    steps:
      - name: Squash & Merge
        id: squashmerge
        if: contains(github.event.comment.body, '/merge') 
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "(#${{ github.event.issue.number }})  ${{ github.event.issue.title }}"
          MERGE_REMOVE_LABELS: "automerge"
  lock_PR:
    needs: squash_merge
    runs-on: ubuntu-latest
    steps:
      - name: lock PR
        if: ${{ needs.squash_merge.outputs.merged == "merged" }}
        uses: sudo-bot/action-pull-request-lock@v1.1.0
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
  
