name: Member

on:
  pull_request:
    branches:
    - 'dev'

jobs:
  php-cs-fixer:
    uses: ./.github/workflows/phpcsfix.yml
  composer-optimize:
    uses: ./.github/workflows/opetimize-composer.yml
