name: Fixer, Styling & Optimizer

on: [workflow_dispatch]

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer install
      - run: composer run csfix
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Fixed by `php-cs-fixer`"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

  format-view:
    needs: [php-cs-fixer, composer-update-optimize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: donjo-app/Views/**
      - if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for i in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
          npm run format $i
          done
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Format view"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

  composer-update-optimize:
    needs: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer update --no-dev
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Composer optimize"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
