name: Fixer, Styling & Optimizer

on:
  issue_comment:

jobs:
  php-cs-fixer:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/format') &&
      github.event.comment.user.id == 2387514
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: composer install
      - run: composer run csfix
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fixed by `php-cs-fixer`

  format-view:
    needs: [php-cs-fixer, composer-update-optimize]
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - run: npm ci
      - id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: donjo-app/Views/**
      - if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for i in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
          npm run format $i
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format View

  composer-update-optimize:
    needs: php-cs-fixer
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: composer update --no-dev
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dependency & optimize composer
