name: Deploy

on:
  issue_comment:
    types:
    - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy'}}
    steps:
      - run: echo "(#${{ github.event.pull_request.number }})  ${{ github.event.pull_request.title }}"
