name: Deploy

on:
  issue_comment:
    types:
    - created

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
      - run: echo "(#${{ github.event.pull_request.number }})  ${{ github.event.pull_request.title }}"
