name: Merge

on:
  pull_request:
    branches:
    - dev
    - automerge

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
      - run: echo "(#${{ github.event.pull_request.number }})  ${{ github.event.pull_request.title }}"
