name: Format Kode

on:
  pull_request:
    branches:
    - 'dev'
  pull_request_review:
    types: [submitted]

jobs:
  cek:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "$({{ github.event.pull_request.number }})  ${{ github.event.pull_request.title }}"
#   automerge:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.review.state == 'approved' }}
#     steps:
#       - uses: "pascalgn/automerge-action@v0.15.5"
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#           MERGE_METHOD: "squash",
#           MERGE_COMMIT_MESSAGE: "(${{ github.event.pull_request.number }})" ${{ github.event.pull_request.title }}
