name: Merge

on:
  pull_request:
    branches:
    - dev
    - automerge

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
      - run: echo "(#${{ github.event.pull_request.number }})  ${{ github.event.pull_request.title }}"
  prcommented:
    needs: pr_commented
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
