name: Composer optimize

on:
  workflow_dispatch:
  workflow_call:

jobs:    
  composer-update-optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: composer update --no-dev
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dependency & optimize composer
