name: Style & Optimize

on:
  pull_request:
    branches:
    - 'dev'
    paths:
      - '!donjo-app/Views/**'
      - '!.github/**'
  pull_request_review:
    types: [submitted]

jobs:          
  php-cs-fixer:
    if: ${{ github.repository == 'ataslangit/sistem-informasi-desa' && github.event.review.state == 'approved' }}
    uses: ./.github/workflows/phpcsfix.yml
  composer-optimize:
    needs: php-cs-fixer
    uses: ./.github/workflows/optimize-composer.yml
