name: PHP-CS-FIXER

on:
  workflow_dispatch:

jobs:    
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: composer install
      - run: composer csfix
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fixed by `php-cs-fixer`
