name: PHPMD

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  schedule:
    - cron: "19 21 * * 4"

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@aa1fe473f9c687b6fb896056d771232c0bc41161
        with:
          php-version: "7.4"

      - name: composer Install
        run: composer install

      - name: Run PHPMD
        run: ./donjo-sys/bin/phpmd donjo-app sarif cleancode --reportfile phpmd-results.sarif
        # continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: phpmd-results.sarif
          wait-for-processing: true
