name: PULL_REQUEST

on:
  pull_request_review:
    types: [submitted]

permissions:
  actions: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: MERGE & LOCK
    runs-on: ubuntu-22.04
    if: >-
      github.event.review.state == 'APPROVED' &&
      github.event.review.user.id == 2387514
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Squash & Merge
        uses: "pascalgn/automerge-action@v0.15.5"
        id: squashmerge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_LABELS: "dependencies"
          MERGE_COMMIT_MESSAGE: "(#${{ github.event.issue.number }})  ${{ github.event.issue.title }}"
          
      - if: ${{ steps.squashmerge.outputs.mergeResult == 'merged' }}
        name: lock PR
        run: gh pr lock ${{ github.event.issue.number }} -r "resolved"
