name: Psalm
permissions:
  contents: read

on:
  pull_request:
    branches:
      - "4.5.x"
    paths:
      - ".github/workflows/psalm.yml"
      - "composer.json"
      - "**.php"
      - "!donjo-app/Views/**"

jobs:
  build:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Install Dependency
        run: composer install

      - name: Run Psalm
        id: psalm
        continue-on-error: true
        run: composer run psalm -- --report=psalm_report.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: psalm_report.sarif
